#!/bin/sh

[ -f /etc/resize-rootfs-disabled -o -f /etc/resized-rootfs ] && exit 0

rootdev=$(awk '$2 == "/" { print $1 }' < /proc/mounts)
out=$(resize2fs "${rootdev}" 2>&1)
if [ $? -ne 0 ]; then
    echo "resize-rootfs: resize failed: $out"
    exit 1
fi

touch /etc/resized-rootfs
