#!/bin/sh
set -e

PREREQS=""
case $1 in
    prereqs) echo "${PREREQS}"; exit 0;;
esac

. /usr/share/initramfs-tools/hook-functions

##
[ -f /etc/resized-rootfs ] && copy_file flag /etc/resized-rootfs
copy_exec /usr/bin/lsblk /usr/bin
